export const CHANGE_FLOW = 'ONBOARDING::CHANGE_FLOW';
export const SET_PIN_CODE = 'ONBOARDING::SET_PIN_CODE';

export const REGISTER = 'ONBOARDING::REGISTER';
export const REGISTER_FAILED = 'ONBOARDING::REGISTER_FAILED';

export const LOGIN = 'ONBOARDING::LOGIN';
export const LOGIN_FAILED = 'ONBOARDING::LOGIN_FAILED';

export const REGISTER_PROFILE = 'ONBOARDING::REGISTER_PROFILE';
export const REGISTER_PROFILE_FAILED = 'ONBOARDING::REGISTER_PROFILE_FAILED';

export const LOOKUP_RESULTS = 'ONBOARDING::LOOKUP_RESULTS';
export const LOOKUP_NOOP = 'ONBOARDING::LOOKUP_NOOP';

export const ONBOARDING_DISMISSED = 'ONBOARDING::DISMISSED';

export const SET_LOGIN_IDENTITY = 'ONBOARDING::SET_LOGIN_IDENTITY';
